# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='usuario',
        ),
    ]
