# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170612_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='usuario',
            new_name='user',
        ),
    ]
